using System.Diagnostics;
using System.IO;
using System.Xml.Serialization;

namespace HudLibFontGen
{
    /// <summary>
    /// Generates font data by using BmFontGen to generate font atlases for the specified style,
    /// parsing the XML data for information on the atlases before deleting the original XML.
    /// </summary>
    public partial class FontData
    {
        /// <summary>
        /// Style ID corresponding to the font style of the atlases generated
        /// </summary>
        public readonly int styleId;

        /// <summary>
        /// Parsed XML Font data generated by BmFontGen
        /// </summary>
        public BmGenData BmData => bmData;

        /// <summary>
        /// Console output from BmFontGen
        /// </summary>
        public string ConsoleOutput { get; private set; }

        private readonly FontGenForm form;
        private readonly BmGenData bmData;
        private readonly Vector2 padding;
        private readonly string xmlPath;

        public FontData(FontGenForm form, Vector2 padding, int styleId)
        {
            this.form = form;
            this.padding = padding;
            this.styleId = styleId;
            xmlPath = $"{form.CustomFontName}\\{form.CustomFontName}-{styleId}.xml";

            GetFontStyle();
            TryGetFontData(out bmData);
        }

        /// <summary>
        /// Generates font atlases and XML data using BmFontGen
        /// </summary>
        private void GetFontStyle()
        {
            Process bmProc = new Process();

            bmProc.StartInfo.CreateNoWindow = true;
            bmProc.StartInfo.UseShellExecute = false;
            bmProc.StartInfo.RedirectStandardOutput = true;
            bmProc.StartInfo.RedirectStandardError = true;
            bmProc.StartInfo.FileName = $"{form.BmGenDir}\\bmfontgen.exe";
            bmProc.StartInfo.Arguments = GetFontGenArgs();
            bmProc.Start();

            ConsoleOutput = bmProc.StandardOutput.ReadToEnd() + bmProc.StandardError.ReadToEnd();
            bmProc.WaitForExit();
        }

        /// <summary>
        /// Generates arguments for BmFontGen based the configuration specified by the form UI
        /// </summary>
        private string GetFontGenArgs()
        {
            string args =
                $"-name \"{form.SelectedFont.Name}\" " +
                $"-size {form.SelectedFont.SizeInPoints} " +
                $"-output \"{form.CustomFontName}\\{form.CustomFontName}-{styleId}\" " +
                GetFontStyleArgs() +
                $"-gpadx {padding.X} -gpady {padding.Y} " +
                "-bmsize 1024 " +
                $"-optfile \"{form.WorkingDir}\\Options\\range.txt\"";

            return args;
        }

        /// <summary>
        /// Converts font style into equivalent BmFontGen args
        /// </summary>
        private string GetFontStyleArgs()
        {
            string args = "";

            if ((styleId & 1) == 1)
                args += "-bold ";

            if ((styleId & 2) == 2)
                args += "-italic ";

            if ((styleId & 4) == 4)
                args += "-underline ";

            if ((styleId & 8) == 8)
                args += "-strikeout ";

            return args;
        }

        /// <summary>
        /// Reads XML generated by BmFontGen, parses it into <see cref="BmGenData"/>, and
        /// deletes the original.
        /// </summary>
        private bool TryGetFontData(out BmGenData data)
        {
            bool success = true;
            data = null;

            try
            {
                XmlSerializer dataSerializer = new XmlSerializer(typeof(BmGenData));

                using (StringReader xml = new StringReader(GetCleanXml()))
                {
                    data = (BmGenData)dataSerializer.Deserialize(xml);
                }

                File.Delete(xmlPath);
            }
            catch
            {
                success = false;
            }

            return success;
        }

        private string GetCleanXml()
        {
            string data;

            using (StreamReader reader = new StreamReader(xmlPath))
            {
                data = reader.ReadToEnd();
            }

            if (data != null)
            {
                int start = -1, end = -1;

                for (int n = 0; n < data.Length - 6; n++)
                {
                    if (start == -1) // because namespaces are evil, I guess
                    {
                        if (data.Substring(n, 7) == "xmlns=\"")
                        {
                            start = n;
                            n += 6;
                        }
                    }
                    else if (end == -1 && data[n] == '\"')
                    {
                        end = n;
                        break;
                    }
                }

                if (start > 0)
                    data = data.Remove(start, end - start + 1);
            }

            return data;
        }
    }
}